export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL'
export const USER_SIGNOUT = 'USER_SIGNOUT'

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'


export const ADD_TUTORIAL_FAIL='ADD_TUTORIAL_FAIL'
export const ADD_TUTORIAL_REQUEST='ADD_TUTORIAL_REQUEST'
export const ADD_TUTORIAL_SUCCESS ='ADD_TUTORIAL_SUCCESS'

export const FETCH_TUTORIAL_FAIL= 'FETCH_TUTORIAL_FAIL'
export const  FETCH_TUTORIAL_REQUEST='FETCH_TUTORIAL_REQUEST'
export const FETCH_TUTORIAL_SUCCESS='FETCH_TUTORIAL_SUCCESS'


export const UPDATE_TUTORIAL_FAIL= 'UPDATE_TUTORIAL_FAIL'
export const  UPDATE_TUTORIAL_REQUEST='UPDATE_TUTORIAL_REQUEST'
export const UPDATE_TUTORIAL_SUCCESS='UPDATE_TUTORIAL_SUCCESS'


export const ADD_SUBJECT_FAIL='ADD_SUBJECT_FAIL'
export const ADD_SUBJECT_REQUEST='ADD_SUBJECT_REQUEST'
export const ADD_SUBJECT_SUCCESS ='ADD_SUBJECT_SUCCESS'

export const FETCH_SUBJECT_FAIL= 'FETCH_SUBJECT_FAIL'
export const  FETCH_SUBJECT_REQUEST='FETCH_SUBJECT_REQUEST'
export const FETCH_SUBJECT_SUCCESS='FETCH_SUBJECT_SUCCESS'

export const UPDATE_SUBJECT_FAIL='UPDATE_SUBJECT_FAIL'
export const UPDATE_SUBJECT_REQUEST='UPDATE_SUBJECT_REQUEST'
export const UPDATE_SUBJECT_SUCCESS ='UPDATE_SUBJECT_SUCCESS'



export const ADD_QUIZ_QUESTION_FAIL='ADD_QUIZ_QUESTION_FAIL'
export const ADD_QUIZ_QUESTION_REQUEST='ADD_QUIZ_QUESTION_REQUEST'
export const ADD_QUIZ_QUESTION_SUCCESS ='ADD_QUIZ_QUESTION_SUCCESS'

export const FETCH_QUIZ_QUESTION_FAIL= 'FETCH_QUIZ_QUESTION_FAIL'
export const  FETCH_QUIZ_QUESTION_REQUEST='FETCH_QUIZ_QUESTION_REQUEST'
export const FETCH_QUIZ_QUESTION_SUCCESS='FETCH_QUIZ_QUESTION_SUCCESS'


export const ADD_REFERENCE_FAIL='ADD_REFERENCE_FAIL'
export const ADD_REFERENCE_REQUEST='ADD_REFERENCE_REQUEST'
export const ADD_REFERENCE_SUCCESS ='ADD_REFERENCE_SUCCESS'

export const FETCH_REFERENCE_FAIL= 'FETCH_REFERENCE_FAIL'
export const  FETCH_REFERENCE_REQUEST='FETCH_REFERENCE_REQUEST'
export const FETCH_REFERENCE_SUCCESS='FETCH_REFERENCE_SUCCESS'


export const UPDATE_REFERENCE_FAIL= 'UPDATE_REFERENCE_FAIL'
export const  UPDATE_REFERENCE_REQUEST='UPDATE_REFERENCE_REQUEST'
export const UPDATE_REFERENCE_SUCCESS='UPDATE_REFERENCE_SUCCESS'


export const PAYMENT_ADD_REQUEST = 'PAYMENT_ADD_REQUEST'
export const PAYMENT_ADD_SUCCESS = 'PAYMENT_ADD_SUCCESS'
export const PAYMENT_ADD_FAIL = 'PAYMENT_ADD_FAIL'

export const CONFIRM_OTP_REQUEST = 'CONFIRM_OTP_REQUEST'
export const CONFIRM_OTP_SUCCESS = 'CONFIRM_OTP_SUCCESS'
export const CONFIRM_OTP_FAIL = 'CONFIRM_OTP_FAIL'


export const ADMIN_COURSEADD_REQUEST='ADMIN_COURSEADD_REQUEST'
export const ADMIN_COURSEADD_SUCCESS='ADMIN_COURSEADD_SUCCESS'
export const ADMIN_COURSEADD_FAIL='ADMIN_COURSEADD_FAIL'
export const ADMIN_COURSEADD_RESET='ADMIN_COURSEADD_RESET'


export const CONFIRM_CHECK_PAY_REQUEST= 'CONFIRM_CHECK_PAY_REQUEST'
export const CONFIRM_CHECK_PAY_SUCCESS='CONFIRM_CHECK_PAY_SUCCESS'
export const CONFIRM_CHECK_PAY_FAIL='CONFIRM_CHECK_PAY_FAIL'
